# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      types: [review_requested, ready_for_review]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      # Configuring ojodb access for github actions
      OJO_HOST: ${{ secrets.OJO_HOST }}
      OJO_PORT: ${{ secrets.OJO_PORT }}
      OJO_DEFAULT_USER: ${{ secrets.OJO_DEFAULT_USER }}
      OJO_DEFAULT_PASS: ${{ secrets.OJO_DEFAULT_PASS }}
      OJO_SSL_MODE: ${{ secrets.OJO_SSL_MODE }}
      # Encoded secrets
      OJO_SSL_CERT_BASE64: ${{ secrets.OJO_SSL_CERT_BASE64 }}
      OJO_SSL_ROOT_CERT_BASE64: ${{ secrets.OJO_SSL_ROOT_CERT_BASE64 }}
      OJO_SSL_KEY_BASE64: ${{ secrets.OJO_SSL_KEY_BASE64 }}
      #
      OJO_SSL_CERT: ${{ github.workspace }}/certs/client-cert.pem
      OJO_SSL_ROOT_CERT: ${{ github.workspace }}/certs/server-ca.pem
      OJO_SSL_KEY: ${{ github.workspace }}/certs/client-key.pk8
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Decode secrets
        shell: bash
        run: |
          mkdir certs
          echo "$OJO_SSL_CERT_BASE64" | base64 --decode > certs/client-cert.pem
          echo "$OJO_SSL_ROOT_CERT_BASE64" | base64 --decode > certs/server-ca.pem
          echo "$OJO_SSL_KEY_BASE64" | base64 --decode > certs/client-key.pk8
          chmod 0600 certs/client-key.pk8

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
